-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.customers DROP CONSTRAINT IF EXISTS customers_user_id_fkey;

ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS orders_area_id_fkey;

ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS orders_customer_id_fkey;

ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS orders_driver_id_fkey;

ALTER TABLE IF EXISTS public.sessions DROP CONSTRAINT IF EXISTS sessions_user_id_fkey;



DROP TABLE IF EXISTS public.areas;

CREATE TABLE IF NOT EXISTS public.areas
(
    id smallserial NOT NULL,
    name character varying(15) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT areas_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.customers;

CREATE TABLE IF NOT EXISTS public.customers
(
    id smallserial NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    user_id smallint NOT NULL DEFAULT 0,
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.drivers;

CREATE TABLE IF NOT EXISTS public.drivers
(
    id smallserial NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT drivers_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.orders;

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    customer_id smallint NOT NULL,
    area_id smallint NOT NULL DEFAULT 0,
    fare integer NOT NULL,
    driver_id smallint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

DROP TABLE IF EXISTS public.sessions;

CREATE TABLE IF NOT EXISTS public.sessions
(
    id serial NOT NULL,
    user_id smallint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expired_at timestamp with time zone,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id smallserial NOT NULL,
    username character varying(15) COLLATE pg_catalog."default",
    password character varying(15) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.customers
    ADD CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_area_id_fkey FOREIGN KEY (area_id)
    REFERENCES public.areas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_driver_id_fkey FOREIGN KEY (driver_id)
    REFERENCES public.drivers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;